"use client";

import { useState } from "react";
import ToolPageLayout from "../../../components/ToolPageLayout";
import { useOptionalI18n } from "../../../i18n/I18nProvider";

type Mode = "encrypt" | "decrypt";

const bytesToBase64 = (bytes: Uint8Array) => {
  let binary = "";
  const chunkSize = 0x8000;
  for (let offset = 0; offset < bytes.length; offset += chunkSize) {
    const chunk = bytes.subarray(offset, offset + chunkSize);
    binary += String.fromCharCode(...chunk);
  }
  return btoa(binary);
};

const base64ToBytes = (base64: string) => {
  const normalized = base64.replace(/\s+/g, "");
  const binary = atob(normalized);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i);
  return bytes;
};

type PayloadV1 = {
  v: 1;
  alg: "AES-256-GCM";
  kdf: "PBKDF2-SHA256";
  iter: number;
  salt: string;
  iv: string;
  ct: string;
};

const toArrayBuffer = (bytes: Uint8Array) => {
  const buffer = new ArrayBuffer(bytes.byteLength);
  new Uint8Array(buffer).set(bytes);
  return buffer;
};

const deriveAesKey = async (password: string, salt: Uint8Array, iterations: number) => {
  const baseKey = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(password),
    "PBKDF2",
    false,
    ["deriveKey"],
  );
  return crypto.subtle.deriveKey(
    {
      name: "PBKDF2",
      hash: "SHA-256",
      salt: toArrayBuffer(salt),
      iterations,
    },
    baseKey,
    { name: "AES-GCM", length: 256 },
    false,
    ["encrypt", "decrypt"],
  );
};

export default function Aes256Client() {
  const i18n = useOptionalI18n();
  const locale = i18n?.locale ?? "zh-cn";
  const ui =
    locale === "en-us"
      ? {
          encrypt: "Encrypt",
          decrypt: "Decrypt",
          iterations: "Iterations",
          plaintext: "Plaintext",
          ciphertextJson: "Ciphertext (JSON from this tool)",
          outputJson: "Encrypted output (decryptable JSON)",
          outputPlaintext: "Decrypted plaintext",
          copy: "Copy",
          run: "Run",
          working: "Working...",
          password: "Password",
          passwordPlaceholder: "Used locally only, never uploaded",
          inputEncryptPlaceholder: "Enter text to encrypt...",
          inputDecryptPlaceholder: "Paste the JSON output from Encrypt...",
          outputPlaceholder: "Click “Run” to generate the result...",
          errorPrefix: "Error:",
          errPasswordRequired: "Please enter a password (used to derive the key).",
          errEncryptFailed: "Encryption failed",
          errDecryptFailed:
            "Decryption failed (wrong password or corrupted payload)",
          errNotToolJson:
            "Input is not a payload generated by this tool (v=1 / AES-256-GCM / PBKDF2-SHA256).",
          errInvalidIter: "Invalid iter",
          errMissingFields: "Missing salt/iv/ct fields",
          explainTitle: "The actual ciphertext is ct inside the JSON",
          explainBody:
            "AES-GCM requires an IV. The key is derived from your password via PBKDF2(salt, iter). We pack ct/iv/salt/iter into JSON so it’s easy to copy, store, and restore.",
          fieldCt: "ct (ciphertext, Base64)",
          fieldIv: "iv (nonce/IV, Base64)",
          fieldSalt: "salt (random salt, Base64)",
          fieldIter: "iter (PBKDF2 iterations)",
          hint:
            "Tip: This tool generates random salt and iv each time. The encrypted output includes all required parameters. For sensitive data, avoid weak algorithms like DES.",
        }
      : {
          encrypt: "加密",
          decrypt: "解密",
          iterations: "迭代次数",
          plaintext: "明文",
          ciphertextJson: "密文（本工具输出的 JSON）",
          outputJson: "加密输出（可解密 JSON）",
          outputPlaintext: "解密结果（明文）",
          copy: "复制",
          run: "执行",
          working: "处理中…",
          password: "密码",
          passwordPlaceholder: "仅在本地使用，不会上传",
          inputEncryptPlaceholder: "输入要加密的文本…",
          inputDecryptPlaceholder: "粘贴加密输出的 JSON…",
          outputPlaceholder: "点击“执行”后显示结果…",
          errorPrefix: "错误：",
          errPasswordRequired: "请输入密码（用于派生密钥）",
          errEncryptFailed: "加密失败",
          errDecryptFailed: "解密失败（可能密码不正确或内容损坏）",
          errNotToolJson: "输入不是本工具生成的 AES256 JSON（v=1 / AES-256-GCM / PBKDF2-SHA256）",
          errInvalidIter: "无效 iter",
          errMissingFields: "缺少 salt/iv/ct 字段",
          explainTitle: "你看到的 JSON 里真正的密文是 ct",
          explainBody:
            "AES-GCM 解密需要 iv，密钥由密码通过 PBKDF2(salt, iter) 派生，所以把 ct/iv/salt/iter 打包成 JSON 便于复制与还原。",
          fieldCt: "ct（密文 Base64）",
          fieldIv: "iv（随机向量 Base64）",
          fieldSalt: "salt（随机盐 Base64）",
          fieldIter: "iter（PBKDF2 迭代次数）",
          hint:
            "提示：此工具使用随机 salt 与 iv；加密输出包含必要参数。建议不要使用 DES 等弱算法进行敏感数据加密。",
        };

  const [mode, setMode] = useState<Mode>("encrypt");
  const [password, setPassword] = useState("");
  const [iterations, setIterations] = useState(200_000);
  const [input, setInput] = useState("Hello AES!");
  const [output, setOutput] = useState("");
  const [lastPayload, setLastPayload] = useState<PayloadV1 | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [isWorking, setIsWorking] = useState(false);

  const encrypt = async () => {
    setError(null);
    setOutput("");
    setLastPayload(null);
    if (!password) {
      setError(ui.errPasswordRequired);
      return;
    }
    setIsWorking(true);
    try {
      const salt = crypto.getRandomValues(new Uint8Array(16));
      const iv = crypto.getRandomValues(new Uint8Array(12));
      const key = await deriveAesKey(password, salt, iterations);
      const pt = new TextEncoder().encode(input);
      const ct = await crypto.subtle.encrypt(
        { name: "AES-GCM", iv: toArrayBuffer(iv) },
        key,
        toArrayBuffer(pt),
      );
      const payload: PayloadV1 = {
        v: 1,
        alg: "AES-256-GCM",
        kdf: "PBKDF2-SHA256",
        iter: iterations,
        salt: bytesToBase64(salt),
        iv: bytesToBase64(iv),
        ct: bytesToBase64(new Uint8Array(ct)),
      };
      setLastPayload(payload);
      setOutput(JSON.stringify(payload, null, 2));
    } catch (e) {
      setError(e instanceof Error ? e.message : ui.errEncryptFailed);
    } finally {
      setIsWorking(false);
    }
  };

  const decrypt = async () => {
    setError(null);
    setOutput("");
    setLastPayload(null);
    if (!password) {
      setError(ui.errPasswordRequired);
      return;
    }
    setIsWorking(true);
    try {
      const parsed = JSON.parse(input) as Partial<PayloadV1>;
      if (parsed.v !== 1 || parsed.alg !== "AES-256-GCM" || parsed.kdf !== "PBKDF2-SHA256") {
        setError(ui.errNotToolJson);
        return;
      }
      const iter = Number(parsed.iter);
      if (!Number.isFinite(iter) || iter < 1) {
        setError(ui.errInvalidIter);
        return;
      }
      if (!parsed.salt || !parsed.iv || !parsed.ct) {
        setError(ui.errMissingFields);
        return;
      }
      const salt = base64ToBytes(parsed.salt);
      const iv = base64ToBytes(parsed.iv);
      const ct = base64ToBytes(parsed.ct);
      const key = await deriveAesKey(password, salt, iter);

      const pt = await crypto.subtle.decrypt(
        { name: "AES-GCM", iv: toArrayBuffer(iv) },
        key,
        toArrayBuffer(ct),
      );
      const text = new TextDecoder().decode(new Uint8Array(pt));
      setOutput(text);
    } catch (e) {
      setError(e instanceof Error ? e.message : ui.errDecryptFailed);
    } finally {
      setIsWorking(false);
    }
  };

  const run = async () => {
    if (mode === "encrypt") await encrypt();
    else await decrypt();
  };

  const copy = async () => {
    await navigator.clipboard.writeText(output);
  };

  const copyText = async (text: string) => {
    await navigator.clipboard.writeText(text);
  };

  return (
    <ToolPageLayout toolSlug="aes256">
      <div className="mt-8 glass-card rounded-3xl p-6 shadow-2xl ring-1 ring-black/5">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="flex rounded-2xl bg-slate-100/60 p-1">
            <button
              type="button"
              onClick={() => {
                setMode("encrypt");
                setOutput("");
                setLastPayload(null);
                setError(null);
              }}
              className={`rounded-xl px-4 py-2 text-sm font-medium transition ${
                mode === "encrypt"
                  ? "bg-white text-slate-900 shadow-sm"
                  : "text-slate-600 hover:text-slate-900"
              }`}
            >
              {ui.encrypt}
            </button>
            <button
              type="button"
              onClick={() => {
                setMode("decrypt");
                setOutput("");
                setLastPayload(null);
                setError(null);
              }}
              className={`rounded-xl px-4 py-2 text-sm font-medium transition ${
                mode === "decrypt"
                  ? "bg-white text-slate-900 shadow-sm"
                  : "text-slate-600 hover:text-slate-900"
              }`}
            >
              {ui.decrypt}
            </button>
          </div>

          <div className="flex flex-wrap items-center gap-3">
            <label className="flex items-center gap-2 text-sm text-slate-700">
              {ui.iterations}
              <input
                type="number"
                min={10_000}
                max={2_000_000}
                value={iterations}
                onChange={(e) => setIterations(Number(e.target.value))}
                className="w-40 rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900 outline-none transition focus:border-blue-400 focus:ring-2 focus:ring-blue-400/30"
              />
            </label>
          </div>
        </div>

        <div className="mt-6 grid gap-4 lg:grid-cols-2">
          <div>
            <div className="mb-2 text-sm font-semibold text-slate-900">
              {mode === "encrypt" ? ui.plaintext : ui.ciphertextJson}
            </div>
            <textarea
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder={
                mode === "encrypt" ? ui.inputEncryptPlaceholder : ui.inputDecryptPlaceholder
              }
              className="h-80 w-full resize-none rounded-2xl border border-slate-200 bg-white px-4 py-3 font-mono text-xs text-slate-900 outline-none transition focus:border-blue-400 focus:ring-2 focus:ring-blue-400/30"
            />
          </div>
          <div>
            <div className="mb-2 flex items-center justify-between gap-2">
              <div className="text-sm font-semibold text-slate-900">
                {mode === "encrypt" ? ui.outputJson : ui.outputPlaintext}
              </div>
              <button
                type="button"
                disabled={!output}
                onClick={copy}
                className="rounded-xl bg-slate-100 px-3 py-2 text-xs font-medium text-slate-800 transition hover:bg-slate-200 disabled:opacity-60"
              >
                {ui.copy}
              </button>
            </div>
            <textarea
              value={output}
              readOnly
              placeholder={ui.outputPlaceholder}
              className="h-80 w-full resize-none rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 font-mono text-xs text-slate-900 outline-none"
            />

            {mode === "encrypt" && lastPayload && (
              <div className="mt-4 rounded-3xl bg-white p-5 ring-1 ring-slate-200">
                <div className="text-sm font-semibold text-slate-900">{ui.explainTitle}</div>
                <p className="mt-1 text-xs text-slate-500">{ui.explainBody}</p>

                <div className="mt-4 grid gap-3 md:grid-cols-2">
                  <div className="space-y-1">
                    <div className="flex items-center justify-between gap-2">
                      <div className="text-xs font-semibold text-slate-700">{ui.fieldCt}</div>
                      <button
                        type="button"
                        onClick={() => void copyText(lastPayload.ct)}
                        className="rounded-lg bg-slate-100 px-2.5 py-1.5 text-[11px] font-medium text-slate-800 hover:bg-slate-200"
                      >
                        {ui.copy}
                      </button>
                    </div>
                    <input
                      value={lastPayload.ct}
                      readOnly
                      className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 font-mono text-xs text-slate-900 outline-none"
                    />
                  </div>

                  <div className="space-y-1">
                    <div className="flex items-center justify-between gap-2">
                      <div className="text-xs font-semibold text-slate-700">{ui.fieldIv}</div>
                      <button
                        type="button"
                        onClick={() => void copyText(lastPayload.iv)}
                        className="rounded-lg bg-slate-100 px-2.5 py-1.5 text-[11px] font-medium text-slate-800 hover:bg-slate-200"
                      >
                        {ui.copy}
                      </button>
                    </div>
                    <input
                      value={lastPayload.iv}
                      readOnly
                      className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 font-mono text-xs text-slate-900 outline-none"
                    />
                  </div>

                  <div className="space-y-1">
                    <div className="flex items-center justify-between gap-2">
                      <div className="text-xs font-semibold text-slate-700">{ui.fieldSalt}</div>
                      <button
                        type="button"
                        onClick={() => void copyText(lastPayload.salt)}
                        className="rounded-lg bg-slate-100 px-2.5 py-1.5 text-[11px] font-medium text-slate-800 hover:bg-slate-200"
                      >
                        {ui.copy}
                      </button>
                    </div>
                    <input
                      value={lastPayload.salt}
                      readOnly
                      className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 font-mono text-xs text-slate-900 outline-none"
                    />
                  </div>

                  <div className="space-y-1">
                    <div className="flex items-center justify-between gap-2">
                      <div className="text-xs font-semibold text-slate-700">{ui.fieldIter}</div>
                      <button
                        type="button"
                        onClick={() => void copyText(String(lastPayload.iter))}
                        className="rounded-lg bg-slate-100 px-2.5 py-1.5 text-[11px] font-medium text-slate-800 hover:bg-slate-200"
                      >
                        {ui.copy}
                      </button>
                    </div>
                    <input
                      value={String(lastPayload.iter)}
                      readOnly
                      className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 font-mono text-xs text-slate-900 outline-none"
                    />
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>

        <div className="mt-4 flex flex-wrap items-center gap-3 rounded-2xl bg-white/60 p-4 ring-1 ring-black/5">
          <label className="flex flex-1 items-center gap-2 text-sm text-slate-700">
            {ui.password}
            <input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900 outline-none transition focus:border-blue-400 focus:ring-2 focus:ring-blue-400/30"
              placeholder={ui.passwordPlaceholder}
            />
          </label>
          <button
            type="button"
            onClick={run}
            disabled={isWorking}
            className="rounded-2xl bg-blue-600 px-6 py-2.5 text-sm font-semibold text-white shadow-lg shadow-blue-500/30 transition hover:bg-blue-700 disabled:opacity-60 active:scale-[0.99]"
          >
            {isWorking ? ui.working : ui.run}
          </button>
        </div>

        {error && (
          <div className="mt-4 text-sm text-rose-600">
            {ui.errorPrefix}
            {error}
          </div>
        )}

        <div className="mt-4 text-xs text-slate-500">{ui.hint}</div>
      </div>
    </ToolPageLayout>
  );
}
